### ISSUE TITLE
upload not working

### ISSUE THREAD

**Issue by AtMostafa** [BeNeuroLab/beneuro_experimental_data_organization#48]
the latest version of bnd: 
![image](https://github.com/BeNeuroLab/beneuro_experimental_data_organization/assets/9393635/5bcb9ef8-08b9-4c6f-ad4c-e3da9d002e39)

**Comment by bagibence** [comment]
Thanks! Yes, that was introduced by exposing running kilosort in the CLI. Should be an easy fix.
