### ISSUE TITLE
Uploading session with missing files to RDS

### ISSUE THREAD

**Issue by CeciliaGallego** [BeNeuroLab/beneuro_experimental_data_organization#52]
If some behavioural files are missing, when trying to upload the session using upload-last, it returns an error and doesn't upload anything. It would be useful if it still raises the error, so the experimenter knows what is missing, but also asks the experimenter if they want to continue with the data upload even if some files are missing.
As it is now, it raises the error and one has to manually upload the files to RDS.

**Comment by bagibence** [comment]
How often does this happen? If only rarely, then I would leave this open for now, because it's not a super straightforward fix, and come back to it if it keeps coming up.

**Comment by CeciliaGallego** [comment]
I think we stopped having this issue (so it doesn't happen often). You can close this issue.
