### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by AtMostafa** [BeNeuroLab/beneuro_experimental_data_organization#61]
a clean env and install works fine. 
when self-updating the following line raises a module not found error for `pydantic`
https://github.com/BeNeuroLab/beneuro_experimental_data_organization/blob/1bb80617a3a8da8e2a2f4d64c616381d0a8fad39/src/beneuro_data/config.py#L3

**Comment by bagibence** [comment]
I haven't been able to reproduce this. Can you please post the steps you did?

**Comment by AtMostafa** [comment]
after `bnd self-update` this happened all the time, even with `bnd --help`
Not critical now, as I did a clean install on the lab computers

**Comment by AtMostafa** [comment]
Just `bnd self-update`. in both lab computers. But as I said I reinstalled them so it's not a issue anymore. if you can't reproduce it, it may be a weird behaviour in the lab?! not sure
