### ISSUE TITLE
Uploading ephys error

### ISSUE THREAD

**Issue by CeciliaGallego** [BeNeuroLab/beneuro_experimental_data_organization#63]
![Capture](https://github.com/user-attachments/assets/da706e10-d6b2-47a7-9aec-ff0a85f3868a)

The ephys data is in: C:\data\raw\M032\M032_2024_07_29_14_30\M032_2024_07_29_14_30_g0

![image](https://github.com/user-attachments/assets/df483dbc-c687-4d38-8654-78b03bac8d89)

**Comment by bagibence** [comment]
Each probe has to have its own subfolder, so you need to put these files into a folder called `M032_2024_07_29_14_30_g0_imec0`

**Comment by AtMostafa** [comment]
It worked!
![image](https://github.com/user-attachments/assets/6afa0414-5ea5-402c-885f-e7db033fbe7c)
Either the efault behaviour changed with the folder structure, or it's becasue of the checkbox I clicked on @CeciliaGallego

**Comment by bagibence** [comment]
Can I close this then?

**Comment by CeciliaGallego** [comment]
Yees, close this pls
