### ISSUE TITLE
Camera naming convention too strict

### ISSUE THREAD

**Issue by martinesparza** [BeNeuroLab/beneuro_experimental_data_organization#73]
When using `bnd up` from the behavioural pc, the default option is correctly set to adding videos. However the video naming system enforces each video to be named with the session:
```shell
Video filename does not start with M041_2024_09_04_10_00_camera_:
D:\data\raw\M041\M041_2024_09_04_10_00\M041_2024_09_04_10_00_cameras\Camera_0.avi
```
Jarvis doesnt automatically name them so a potential fix could be to remove this rule, or rename the videos.

**Comment by bagibence** [comment]
I think the default is not to include videos: https://github.com/BeNeuroLab/beneuro_experimental_data_organization/blob/ca72897d58a88f413939d792e6cdd3fd1edff650/src/beneuro_data/cli.py#L767

If `include_videos` is true and `rename_videos_first` is not specified, then `rename_videos_first` should be set to true as well and videos should be renamed first.

Does this happen with `bnd upload-session`, too?

**Comment by martinesparza** [comment]
This was fixed just by pulling the latest version onto the lab PCs
