### ISSUE TITLE
Change naming system to provide session only

### ISSUE THREAD

**Issue by martinesparza** [BeNeuroLab/beneuro_experimental_data_organization#75]
Its pretty annoying to provide a full path to the `bnd` functions, especially when some of them require the raw or processed directory. We should implement a change where only the session path is provided, and each function can look in raw or processed depending on the needs.

**Comment by bagibence** [comment]
I'm not sure I understand. Do you mean the `bnd` CLI or the functions behind it? Can you please give an example?

**Comment by martinesparza** [comment]
This done in PR #84
